apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  create_schema.sql: |
    CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  create_table.sql: |
    CREATE TABLE IF NOT EXISTS mydb.users (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, name VARCHAR(50));
