apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      infrastructure: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        infrastructure: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
          - name: init-sql
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: persistent-volume-claim
        - name: init-sql
          configMap:
            name: init-sql
