apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kotlin-app
  template:
    metadata:
      labels:
        app: kotlin-app
    spec:
      containers:
      - name: kotlin-app
        image: 360616033874.dkr.ecr.ap-northeast-1.amazonaws.com/kotlin-app
        ports:
        - containerPort: 8080
