apiVersion: v1
kind: Service
metadata:
  name: kotlin-app
  labels:
    app: kotlin-app
spec:
  type: NodePort
  selector:
    app: kotlin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
